### PR TITLE
chore: rename integrations to add-ons

### PR DESCRIPTION
**Pull request by benmccann**
matches the language used in the announcement blog post

closes https://github.com/sveltejs/cli/issues/82

### CODE REVIEW

**Comment by manuel3108** [comment]
Is there a reason you decided to go with `add-ons` instead of `addons`? Probably from the blog post I imagine. Googeling around a bit it looks like both things are commonly used and i was unable to find any preference for one thing.

I noticed this while looking at the new args and `--no-add-ons` feels wired to me.

Also this PR "only" covers the public facing stuff. We should think about renaming our currently internal stuff to addons as well and potentially create a follow up. Especially in regard to the public facing API i think stuff like `defineAdderOptions` and `defineAdder` do not make much sense.

**Comment by Rich-Harris** [comment]
Add-on is correct!

> `--no-add-ons` feels wired to me

We already use hyphenated flags elsewhere (`--compiler-warnings`, `--diagnostic-sources` etc) so I think it's fine to have another. (Though we do also have `--preserveWatchOutput` which should be updated to match the conventions everywhere else)

**Comment by benmccann** [comment]
`--compiler-warnings`, etc. are replacing a space with a hyphen, which makes sense. I guess the question is if you start out with a hyphen, do you just remove it or leave it as a hyphen? I'm not opposed to `--no-addons`. It does look a bit nicer to me. But I agree that everywhere in text I would leave it as "Add-on", which is much more commonly used

**Review by manuel3108 — APPROVED** [review]

**Comment by Rich-Harris** [comment]
great news, merging this caused https://github.com/sveltejs/svelte.dev/pull/729 to update. PRs will now automatically be created whenever docs changes are merged to main

**Pull request merged**
