### PR TITLE
chore: update `storybook` to v8.4.0

### PR DESCRIPTION
**Pull request by manuel3108**
Relates #296

### CODE REVIEW

**Comment by AdrianGonz97** [comment]
`storybook` has already been set to `@latest` as part of #181, so this PR isn't necessary unless we're wanting to pin it to a specific version again

**Comment by JReinhold** [comment]
If CI has been working with latest, maybe it was a temporary issue?

**Comment by AdrianGonz97** [comment]
#296 was strictly a local issue and was unrelated to CI. In fact, I don't think we ever saw a CI failure as a result of using `@latest`. 

However, #293 _is_ a CI related issue with storybook where we noticed that we can't run our storybook tests concurrently on windows in CI (though, it works fine locally).

**Comment by manuel3108** [comment]
> `storybook` has already been set to `@latest` as part of #181, so this PR isn't necessary unless we're wanting to pin it to a specific version again

Uhh, somehow didn't notice that!

**Pull request closed without merging**
