### PR TITLE
chore: update `unplugin-isolated-decl`

### PR DESCRIPTION
**Pull request by manuel3108**
Problem with package mentioned above first detect in #314. Based on the findings this issue was created: https://github.com/unplugin/unplugin-isolated-decl/issues/34

The generated code now looks fine, but intellisense and `tsc` are still not happy.

The problem assumably arises because the file extensions are now stripped, see [`unplugin-isolated-decl@0.8.1`](https://github.com/unplugin/unplugin-isolated-decl/releases/tag/v0.8.1). Everything seems to be working in the example project provided in the issue mentioned above, but not here.

Let's in example take a look at `packages\core\dist\index.d.ts` (after running `pnpm build` from the root):
```js
export { defineAddon, defineAddonOptions } from './addon/config';
// ...
export * as utils from './utils';
export type * from './addon/processors';
export type * from './addon/options';
// ...
```
Running `pnpm check` or just hovering the mouse over i.e. `defineAddon`, reveals that something is not working as expected. 

Adding `.ts` or `.d.ts` to all relevant import makes the intellisense happy again. The question is why this is happening here and not in the repro project from the issue above.

### CODE REVIEW

**Comment by AdrianGonz97** [comment]
it looks like the file extensions (`.ts`) are being stripped from the generated entry points in the dist: 
img

these extensions are necessary when `moduleResolution` is set to `Node16`

**Comment by sxzz** [comment]
1. Upgrade `unplugin-isolated-decl` to `v0.8.3`.
2. Add `inputBase` option to avoid extra `lib` folder in cli package.
```ts
dts({
	include: project === 'cli' ? [`${projectRoot}/lib/*`] : undefined,
	inputBase: project === 'cli' ? path.resolve(projectRoot, 'lib') : undefined
})
```

Here is the patch.

```diff
From 017ef2b4c31fb8d595ebe2c1d3e5fe5d50b954b5 Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?=E4=B8=89=E5=92=B2=E6=99=BA=E5=AD=90=20Kevin=20Deng?=
 <sxzz@sxzz.moe>
Date: Tue, 26 Nov 2024 00:35:00 +0800
Subject: [PATCH] fix

---
 package.json              |  2 +-
 packages/cli/package.json |  4 ++--
 pnpm-lock.yaml            | 10 +++++-----
 rollup.config.js          |  5 ++++-
 4 files changed, 12 insertions(+), 9 deletions(-)

diff --git a/package.json b/package.json
index bd08b04..ba8b697 100644
--- a/package.json
+++ b/package.json
@@ -41,7 +41,7 @@
 		"svelte": "^5.0.0",
 		"typescript": "^5.6.2",
 		"typescript-eslint": "^8.5.0",
-		"unplugin-isolated-decl": "^0.8.1",
+		"unplugin-isolated-decl": "^0.8.3",
 		"vitest": "^2.1.4"
 	},
 	"packageManager": "pnpm@9.7.0"
diff --git a/packages/cli/package.json b/packages/cli/package.json
index b736009..33caa79 100644
--- a/packages/cli/package.json
+++ b/packages/cli/package.json
@@ -21,11 +21,11 @@
 	"bin": "./dist/bin.js",
 	"exports": {
 		".": {
-			"types": "./dist/lib/index.d.ts",
+			"types": "./dist/index.d.ts",
 			"default": "./dist/index.js"
 		},
 		"./testing": {
-			"types": "./dist/lib/testing.d.ts",
+			"types": "./dist/testing.d.ts",
 			"default": "./dist/testing.js"
 		}
 	},
diff --git a/pnpm-lock.yaml b/pnpm-lock.yaml
index ed6bb0a..4daaaaf 100644
--- a/pnpm-lock.yaml
+++ b/pnpm-lock.yaml
@@ -78,8 +78,8 @@ importers:
         specifier: ^8.5.0
         version: 8.5.0(eslint@9.10.0)(typescript@5.6.3)
       unplugin-isolated-decl:
-        specifier: 0.8.1
-        version: 0.8.1(rollup@4.22.4)(typescript@5.6.3)
+        specifier: ^0.8.3
+        version: 0.8.3(rollup@4.22.4)(typescript@5.6.3)
       vitest:
         specifier: ^2.1.4
         version: 2.1.4(@types/node@22.9.0)(@vitest/ui@2.1.4)
@@ -2393,8 +2393,8 @@ packages:
     resolution: {integrity: sha512-rBJeI5CXAlmy1pV+617WB9J63U6XcazHHF2f2dbJix4XzpUF0RS3Zbj0FGIOCAva5P/d/GBOYaACQ1w+0azUkg==}
     engines: {node: '>= 4.0.0'}
 
-  unplugin-isolated-decl@0.8.1:
-    resolution: {integrity: sha512-sdaVyb8GVkRz/88fqcEHMxB62YYEz8B40qAvAAacgbonzQVq/VLuZ+gjSagtPy9aN9w9LH8x1qTwXP3xApu39g==}
+  unplugin-isolated-decl@0.8.3:
+    resolution: {integrity: sha512-LYtDV91NRRbWBk1wrhTRcXIuK9kM7IQ0Kd+QlKZ2UV3xJ20hQRwuIPEyQbFPRPyN+pct1RZR0C1BrnflbV5jdQ==}
     engines: {node: '>=18.12.0'}
     peerDependencies:
       '@swc/core': ^1.6.6
@@ -4592,7 +4592,7 @@ snapshots:
 
   universalify@0.1.2: {}
 
-  unplugin-isolated-decl@0.8.1(rollup@4.22.4)(typescript@5.6.3):
+  unplugin-isolated-decl@0.8.3(rollup@4.22.4)(typescript@5.6.3):
     dependencies:
       '@rollup/pluginutils': 5.1.3(rollup@4.22.4)
       debug: 4.3.7
diff --git a/rollup.config.js b/rollup.config.js
index 255b49f..224a427 100644
--- a/rollup.config.js
+++ b/rollup.config.js
@@ -113,7 +113,10 @@ function getConfig(project) {
 		plugins: [
 			preserveShebangs(),
 			'exports' in pkg &&
-				dts({ include: project === 'cli' ? [`${projectRoot}/lib/*`] : undefined }),
+				dts({
+					include: project === 'cli' ? [`${projectRoot}/lib/*`] : undefined,
+					inputBase: project === 'cli' ? path.resolve(projectRoot, 'lib') : undefined
+				}),
 			esbuild(),
 			nodeResolve({ preferBuiltins: true, rootDir: projectRoot }),
 			commonjs(),
-- 
2.47.0


```

**Comment by manuel3108** [comment]
> * Upgrade `unplugin-isolated-decl` to `v0.8.3`.
> * Add `inputBase` option to avoid extra `lib` folder in cli package.

That's awesome, thank you so much for your help! Everything seems to be working now locally, and tests seem to be happy too!

**Review by AdrianGonz97 — APPROVED** [review]
this works great now! thank you @sxzz!!

**Pull request merged**
